In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# set up example
# ex_grid = np.array([[[0,1,1,0],[1,0,1,1],[1,1,0,1],[0,1,1,1]]])
grid = np.array([[[0,1,1,0], [1,0,1,1], [1,1,0,1], [0,1,1,1]],
                    [[0,1,1,1], [1,0,0,1], [1,0,0,1], [1,1,1,1]]])
# x, y, direction(axis,dir), counter, state
stats = np.array([(0,0,0,1,0,1), (1,1,0,1,0,1)])
print(grid)
print(stats)

[[[0 1 1 0]
  [1 0 1 1]
  [1 1 0 1]
  [0 1 1 1]]

 [[0 1 1 1]
  [1 0 0 1]
  [1 0 0 1]
  [1 1 1 1]]]
[[0 0 0 1 0 1]
 [1 1 0 1 0 1]]


In [3]:
# get row or column
grid[np.arange(grid.shape[0]), stats[:, 0], :] * (1 - stats[:, 2]).reshape(-1, 1) + \
grid[np.arange(grid.shape[0]), :, stats[:, 0]] * (stats[:, 2]).reshape(-1, 1)

array([[0, 1, 1, 0],
       [1, 0, 0, 1]])

In [4]:
stats[np.arange(stats.shape[0]), stats[:, 2]]

array([0, 1])